@startuml ʕAppℴNameʔ
' uncomment the line below if you're using computer with a retina display
' skinparam dpi 300
!define Table(name,desc) class name as "desc" << (T,#FFAAAA) >>
' we use bold for primary key
' green color for unique
' and underscore for not_null
!define primary_key(x) <b>x</b>
!define unique(x) <color:green>x</color>
!define not_null(x) <u>x</u>
' other tags available:
' <i></i>
' <back:COLOR></color>, where color is a color name or html color code
' (#FFAACC)
' see: http://plantuml.com/classes.html#More
hide methods
hide stereotypes

' entities
ʕfor each Entity in AppℴEntitiesʔ
Table(ʕEntityℴNameʔ, "ʕEntityℴNameʔ\n(ʕEntityℴDescriptionʔ)") {
    ʕfor each Property in EntityℴPropertiesʔʕif PropertyℴIsPrimaryKeyʔprimary_key(ʕPropertyℴNameʔ>) INTEGER
    ʕelse if PropertyℴDataType == DataTypeℴStringʔnot_null(ʕPropertyℴNameʔ) VARCHAR[ʕPropertyℴMaxLengthℴToStringʢʡʔ]
    ʕelse if PropertyℴDataType == DataTypeℴDateTimeʔʕPropertyℴNameʔ DATETIME
    ʕelseʔʕPropertyℴNameʔ ʕPropertyℴDataTypeℴToStringʢʡʔ
    ʕend ifʔʕnext Propertyʔ
}
ʕnext Entityʔ

ʕfor each Entity in AppℴEntitiesʔ
ʕfor each Property as ParentProperty in EntityℴParentPropertiesʔ
ʕParentPropertyℴEntityℴNameʔ --> ʕParentPropertyℴParentℴNameʔ
ʕnext Parentʔ
ʕnext Entityʔ
' ' relationships
' ' one-to-one relationship
' user -- user_profile : "A user only \nhas one profile"
' ' one to may relationship
' user --> session : "A user may have\n many sessions"
' ' many to many relationship
' ' Add mark if you like
' user "1" --> "*" user_group : "A user may be \nin many groups"
' group
'     "1" --> "0..N" user_group : "A group may \ncontain many users"
@enduml